name: "TheTVDB"
guid: "a677c0da-fac5-4cde-941a-7134223f14c8"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-tvdb.png"
version: "9"
targetAbi: "10.7.7.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Get TV metadata from TheTvdb"
description: >
  Get TV metadata from TheTvdb

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.Tvdb.dll"
  - "TvDbSharper.dll"
changelog: |2-
  ### Code or Repo Maintenance ###
  - Use meta ci (#67) @crobibero

  ### CI & build changes ###
  - Use meta ci (#67) @crobibero
